### ISSUE TITLE
Does not seems to work on Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by dgedgedge** [Jerome-Maurin/vmdb2-wrapper#1]
Got the latest release git clone.
Then run the cmd as provided:
```

denis@badday:~/nanopiR1/vmdb2-wrapper$ sudo vmdb2 nanopi-r1_buster_armhf_vmdb2-0.14.1.yaml --output nanopi-r1_buster_armhf.img --rootfs-tarball buster_armhf_rootfs.tgz --log=stderr
INFO vmdb2 version 0.12 starts
DEBUG sys.argv: ['/usr/bin/vmdb2', 'nanopi-r1_buster_armhf_vmdb2-0.14.1.yaml', '--output', 'nanopi-r1_buster_armhf.img', '--rootfs-tarball', 'buster_armhf_rootfs.tgz', '--log=stderr']
DEBUG current working directory: /home/denis/nanopiR1/vmdb2-wrapper
DEBUG uid: 0
DEBUG effective uid: 0
DEBUG gid: 0
DEBUG effective gid: 0
DEBUG environment variables:
DEBUG environment: LANG=fr_FR.UTF-8
DEBUG environment: HOME=/home/denis
DEBUG environment: TERM=xterm-256color
DEBUG environment: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
DEBUG environment: MAIL=/var/mail/root
DEBUG environment: LOGNAME=root
DEBUG environment: USER=root
DEBUG environment: USERNAME=root
DEBUG environment: SHELL=/bin/bash
DEBUG environment: SUDO_COMMAND=/usr/bin/vmdb2 nanopi-r1_buster_armhf_vmdb2-0.14.1.yaml --output nanopi-r1_buster_armhf.img --rootfs-tarball buster_armhf_rootfs.tgz --log=stderr
DEBUG environment: SUDO_USER=denis
DEBUG environment: SUDO_UID=1000
DEBUG environment: SUDO_GID=1000
DEBUG Config:
[config]
output = nanopi-r1_buster_armhf.img
log = stderr
log-level = debug
log-max = 0
log-keep = 10
log-mode = 0600
dump-memory-profile = simple
memory-dump-interval = 300
image = 
verbose = False
size = 1073741824
rootfs-tarball = buster_armhf_rootfs.tgz


DEBUG Python version: 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
INFO Load spec file nanopi-r1_buster_armhf_vmdb2-0.14.1.yaml
CRITICAL Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cliapp/app.py", line 193, in _run
    self.process_args(args)
  File "/usr/lib/python3/dist-packages/vmdb/app.py", line 55, in process_args
    self.step_runners.find(step)
  File "/usr/lib/python3/dist-packages/vmdb/step_list.py", line 70, in find
    raise NoMatchingRunner(actual)
vmdb.step_list.NoMatchingRunner: No runner implements step with keys kpartx

ERROR: No runner implements step with keys kpartx
denis@badday:~/nanopiR1/vmdb2-wrapper$

```

Configuration:

```

denis@badday:~/nanopiR1/vmdb2-wrapper$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic


```

Elements of config:
```
ii  kpartx                                  0.7.4-2ubuntu3           amd64                    create device mappings for partitions
```
```


denis@badday:~/nanopiR1/vmdb2-wrapper$ dpkg -l py* | grep ii
ii  python                               2.7.15~rc1-1                      amd64        interactive high-level object-oriented language (default version)
ii  python-all                           2.7.15~rc1-1                      amd64        package depending on all supported Python runtime versions
ii  python-all-dev                       2.7.15~rc1-1                      amd64        package depending on all supported Python development packages
ii  python-appindicator                  12.10.1+18.04.20180322.1-0ubuntu1 amd64        Python bindings for libappindicator
ii  python-apt                           1.6.5ubuntu0.3                    amd64        Python interface to libapt-pkg
ii  python-apt-common                    1.6.5ubuntu0.3                    all          Python interface to libapt-pkg (locales)
ii  python-aptdaemon                     1.1.1+bzr982-0ubuntu19.4          all          Python 2 module for the server and client of aptdaemon
ii  python-aptdaemon.gtk3widgets         1.1.1+bzr982-0ubuntu19.4          all          Python 2 GTK+ 3 widgets to run an aptdaemon client
ii  python-asn1crypto                    0.24.0-1                          all          Fast ASN.1 parser and serializer (Python 2)
ii  python-attr                          17.4.0-2                          all          Attributes without boilerplate (Python 2)
ii  python-automat                       0.6.0-1                           all          Self-service finite-state machines for the programmer on the go
ii  python-backports.functools-lru-cache 1.4-2                             all          backport of functools.lru_cache from Python 3.3
ii  python-blinker                       1.4+dfsg1-0.1                     all          Fast, simple object-to-object and broadcast signaling library
ii  python-bs4                           4.6.0-1                           all          error-tolerant HTML parser for Python
ii  python-cairo:amd64                   1.16.2-1                          amd64        Python bindings for the Cairo vector graphics library
ii  python-certifi                       2018.1.18-2                       all          root certificates for validating SSL certs and verifying TLS hosts
ii  python-cffi-backend                  1.11.5-1                          amd64        Foreign Function Interface for Python calling C code - backend
ii  python-chardet                       3.0.4-1                           all          universal character encoding detector for Python2
ii  python-cliapp                        1.20170827-1                      all          Python framework for Unix command line programs
ii  python-click                         6.7-3                             all          Simple wrapper around optparse for powerful command line utilities - Python 2.7
ii  python-colorama                      0.3.7-1                           all          Cross-platform colored terminal text in Python - Python 2.x
ii  python-constantly                    15.1.0-1                          all          Symbolic constants in Python
ii  python-crypto                        2.6.1-8ubuntu2                    amd64        cryptographic algorithms and protocols for Python
ii  python-cryptography                  2.1.4-1ubuntu1.3                  amd64        Python library exposing cryptographic recipes and primitives (Python 2)
ii  python-cups                          1.9.73-2                          amd64        Python bindings for CUPS
ii  python-cycler                        0.10.0-1                          all          composable kwarg iterator (Python 2)
ii  python-dateutil                      2.6.1-1                           all          powerful extensions to the standard Python datetime module
ii  python-dbus                          1.2.6-1                           amd64        simple interprocess messaging system (Python interface)
ii  python-dbus-dev                      1.2.6-1                           all          main loop integration development files for python-dbus
ii  python-debian                        0.1.32                            all          Python modules to work with Debian-related data formats
ii  python-defer                         1.0.6-2build1                     all          Small framework for asynchronous programming (Python 2)
ii  python-defusedxml                    0.5.0-1ubuntu1                    all          XML bomb protection for Python stdlib modules (for Python 2)
ii  python-dev                           2.7.15~rc1-1                      amd64        header files and a static library for Python (default)
ii  python-dirspec                       13.10-1ubuntu1                    all          Python User Folders Specification Library
ii  python-dnspython                     1.15.0-1                          all          DNS toolkit for Python
ii  python-enum34                        1.1.6-2                           all          backport of Python 3.4's enum package
ii  python-fasteners                     0.12.0-3                          all          provides useful locks - Python 2.7
ii  python-gconf                         2.28.1+dfsg-1.2                   amd64        Python bindings for the GConf configuration database system
ii  python-gdbm                          2.7.17-1~18.04                    amd64        GNU dbm database support for Python2
ii  python-gi                            3.26.1-2ubuntu1                   amd64        Python 2.x bindings for gobject-introspection libraries
ii  python-gi-cairo                      3.26.1-2ubuntu1                   amd64        Python Cairo bindings for the GObject library
ii  python-glade2                        2.24.0-5.1ubuntu2                 amd64        GTK+ bindings: Glade support
ii  python-gnucash                       1:2.6.19-1                        amd64        Gnucash interface for Python
ii  python-gobject                       3.26.1-2ubuntu1                   all          Python 2.x bindings for GObject - transitional package
ii  python-gobject-2                     2.28.6-12ubuntu3                  amd64        deprecated static Python bindings for the GObject library
ii  python-gst-1.0                       1.14.5-0ubuntu1~18.04.1           amd64        GStreamer GObject Introspection overrides for Python
ii  python-gtk2                          2.24.0-5.1ubuntu2                 amd64        Python bindings for the GTK+ widget set
ii  python-html5lib                      0.999999999-1                     all          HTML parser/tokenizer based on the WHATWG HTML5 specification
ii  python-httplib2                      0.9.2+dfsg-1ubuntu0.2             all          comprehensive HTTP client library written for Python
ii  python-hyperlink                     17.3.1-2                          all          Immutable, Pythonic, correct URLs.
ii  python-idna                          2.6-1                             all          Python IDNA2008 (RFC 5891) handling (Python 2)
ii  python-incremental                   16.10.1-3                         all          Library for versioning Python projects.
ii  python-ipaddress                     1.0.17-1                          all          Backport of Python 3 ipaddress module (Python 2)
ii  python-jinja2                        2.10-1ubuntu0.18.04.1             all          small but fast and easy to use stand-alone template engine
ii  python-jmespath                      0.9.3-1ubuntu1                    all          JSON Matching Expressions (Python 2)
ii  python-jwt                           1.5.3+ds1-1                       all          Python implementation of JSON Web Token
ii  python-kerberos                      1.1.14-1                          amd64        GSSAPI interface module - Python 2.x
ii  python-keyring                       10.6.0-1                          all          store and access your passwords safely
ii  python-keyrings.alt                  3.0-1                             all          alternate backend implementations for python-keyring
ii  python-ldb:amd64                     2:1.2.3-1ubuntu0.1                amd64        Python bindings for LDB
ii  python-libcloud                      2.2.1-1                           all          unified Python interface into the cloud
ii  python-libxml2                       2.9.4+dfsg1-6.1ubuntu1.3          amd64        Python bindings for the GNOME XML library
ii  python-lockfile                      1:0.12.2-2                        all          file locking library for Python — Python 2 library
ii  python-lxml:amd64                    4.2.1-1ubuntu0.1                  amd64        pythonic binding for the libxml2 and libxslt libraries
ii  python-lzma                          0.5.3-3                           amd64        Python bindings for liblzma
ii  python-markdown                      2.6.9-1                           all          text-to-HTML conversion library/tool (Python 2 version)
ii  python-markupsafe                    1.0-1build1                       amd64        HTML/XHTML/XML string library for Python
ii  python-matplotlib                    2.1.1-2ubuntu3                    amd64        Python based plotting system in a style similar to Matlab
ii  python-matplotlib-data               2.1.1-2ubuntu3                    all          Python based plotting system (data package)
ii  python-minimal                       2.7.15~rc1-1                      amd64        minimal subset of the Python language (default version)
ii  python-mlt                           6.6.0-1build1                     amd64        multimedia framework (Python bindings)
ii  python-monotonic                     1.1-2                             all          implementation of time.monotonic() - Python 2.x
ii  python-nautilus                      1.1-6                             amd64        Python binding for Nautilus components
ii  python-netaddr                       0.7.19-1                          all          manipulation of various common network address notations (Python 2)
ii  python-notify                        0.1.1-4                           amd64        Python bindings for libnotify
ii  python-ntdb                          1.0-9build1                       amd64        Python bindings for NTDB
ii  python-numpy                         1:1.13.3-2ubuntu1                 amd64        Numerical Python adds a fast array facility to the Python language
ii  python-oauthlib                      2.0.6-1                           all          generic, spec-compliant implementation of OAuth for Python
ii  python-olefile                       0.45.1-1                          all          Python module to read/write MS OLE2 files
ii  python-openssl                       17.5.0-1ubuntu1                   all          Python 2 wrapper around the OpenSSL library
ii  python-pam                           0.4.2-13.2ubuntu4                 amd64        Python interface to the PAM library
ii  python-paramiko                      2.0.0-1ubuntu1.2                  all          Make ssh v2 connections (Python 2)
ii  python-pexpect                       4.2.1-1                           all          Python module for automating interactive applications
ii  python-pil:amd64                     5.1.0-1ubuntu0.3                  amd64        Python Imaging Library (Pillow fork)
ii  python-pip                           9.0.1-2.3~ubuntu1.18.04.2         all          Python package installer
ii  python-pip-whl                       9.0.1-2.3~ubuntu1.18.04.2         all          Python package installer
ii  python-piston-mini-client            0.7.5-0ubuntu3                    all          library for writing clients for Django's Piston REST APIs
ii  python-pkg-resources                 39.0.1-2                          all          Package Discovery and Resource Access using pkg_resources
ii  python-ptyprocess                    0.5.2-1                           all          Run a subprocess in a pseudo terminal from Python 2
ii  python-pyasn1                        0.4.2-3                           all          ASN.1 library for Python (Python 2 module)
ii  python-pyasn1-modules                0.2.1-0.2                         all          Collection of protocols modules written in ASN.1 language
ii  python-pycurl                        7.43.0.1-0.2                      amd64        Python bindings to libcurl
ii  python-pygments                      2.2.0+dfsg-1                      all          syntax highlighting package written in Python
ii  python-pyparsing                     2.2.0+dfsg1-2                     all          alternative to creating and executing simple grammars - Python 2.7
ii  python-qt4                           4.12.1+dfsg-2                     amd64        Python bindings for Qt4
ii  python-renderpm:amd64                3.4.0-3ubuntu0.1                  amd64        python low level render interface
ii  python-reportlab                     3.4.0-3ubuntu0.1                  all          ReportLab library to create PDF documents using Python
ii  python-reportlab-accel:amd64         3.4.0-3ubuntu0.1                  amd64        C coded extension accelerator for the ReportLab Toolkit
ii  python-requests                      2.18.4-2ubuntu0.1                 all          elegant and simple HTTP library for Python2, built for human beings
ii  python-rope                          0.10.5-2                          all          Python 2 refactoring library
ii  python-samba                         2:4.7.6+dfsg~ubuntu-0ubuntu2.19   amd64        Python bindings for Samba
ii  python-scour                         0.36-2                            all          SVG scrubber and optimizer (Python 2 module)
ii  python-secretstorage                 2.3.1-2                           all          Python module for storing secrets - Python 2.x version
ii  python-selinux                       2.7-2build2                       amd64        Python bindings to SELinux shared libraries
ii  python-serial                        3.4-2                             all          pyserial - module encapsulating access for the serial port
ii  python-service-identity              16.0.0-2                          all          Service identity verification for pyOpenSSL (Python 2 module)
ii  python-setuptools                    39.0.1-2                          all          Python Distutils Enhancements
ii  python-simplejson                    3.13.2-1                          amd64        simple, fast, extensible JSON encoder/decoder for Python 2.x
ii  python-sip                           4.19.7+dfsg-1ubuntu0.1            amd64        Python/C++ bindings generator runtime library
ii  python-six                           1.11.0-2                          all          Python 2 and 3 compatibility library (Python 2 interface)
ii  python-smbc                          1.0.15.6-1build2                  amd64        Python 2 bindings for the Samba client library
ii  python-soappy                        0.12.22-1                         all          SOAP Support for Python
ii  python-subprocess32                  3.2.7-3                           amd64        backport of the Py3 stdlib subprocess module for Py2
ii  python-svn                           1.9.5-1                           amd64        A(nother) Python interface to Subversion
ii  python-talloc                        2.1.10-2ubuntu1                   amd64        hierarchical pool based memory allocator - Python bindings
ii  python-tdb                           1.3.15-2                          amd64        Python bindings for TDB
ii  python-tk                            2.7.17-1~18.04                    amd64        Tkinter - Writing Tk applications with Python2
ii  python-ttystatus                     0.38-1                            all          terminal progress bar and status output for Python
ii  python-twisted-bin:amd64             17.9.0-2ubuntu0.1                 amd64        Event-based framework for internet applications
ii  python-twisted-core                  17.9.0-2ubuntu0.1                 all          Event-based framework for internet applications
ii  python-twisted-web                   17.9.0-2ubuntu0.1                 all          twisted dummy package for HTTP protocol implementation
ii  python-tz                            2018.3-2                          all          Python version of the Olson timezone database
ii  python-urllib3                       1.22-1ubuntu0.18.04.1             all          HTTP library with thread-safe connection pooling for Python
ii  python-webencodings                  0.5-2                             all          Python implementation of the WHATWG Encoding standard
ii  python-wheel                         0.30.0-0.2                        all          built-package format for Python
ii  python-wstools                       0.4.3-3                           all          WSDL parsing tools Python module
ii  python-wxgtk3.0                      3.0.2.0+dfsg-7                    amd64        Python interface to the wxWidgets Cross-platform C++ GUI toolkit
ii  python-wxversion                     3.0.2.0+dfsg-7                    all          API for selecting the wxPython version to use
ii  python-xapian                        1.4.5-1ubuntu3                    amd64        Xapian search engine interface for Python
ii  python-xdg                           0.25-4ubuntu1                     all          Python 2 library to access freedesktop.org standards
ii  python-xmltodict                     0.11.0-1                          all          Makes working with XML feel like you are working with JSON (Python 2)
ii  python-yaml                          3.12-1build2                      amd64        YAML parser and emitter for Python
ii  python-zeitgeist                     1.0-0.1ubuntu1                    all          event logging framework - Python bindings
ii  python-zope.interface                4.3.2-1build2                     amd64        Interfaces for Python
ii  python2.7                            2.7.17-1~18.04ubuntu1.1           amd64        Interactive high-level object-oriented language (version 2.7)
ii  python2.7-dev                        2.7.17-1~18.04ubuntu1.1           amd64        Header files and a static library for Python (v2.7)
ii  python2.7-minimal                    2.7.17-1~18.04ubuntu1.1           amd64        Minimal subset of the Python language (version 2.7)
ii  python3                              3.6.7-1~18.04                     amd64        interactive high-level object-oriented language (default python3 version)
ii  python3-all                          3.6.7-1~18.04                     amd64        package depending on all supported Python 3 runtime versions
ii  python3-all-dev                      3.6.7-1~18.04                     amd64        package depending on all supported Python 3 development packages
ii  python3-apport                       2.20.9-0ubuntu7.17                all          Python 3 library for Apport crash report handling
ii  python3-apt                          1.6.5ubuntu0.3                    amd64        Python 3 interface to libapt-pkg
ii  python3-aptdaemon                    1.1.1+bzr982-0ubuntu19.4          all          Python 3 module for the server and client of aptdaemon
ii  python3-aptdaemon.gtk3widgets        1.1.1+bzr982-0ubuntu19.4          all          Python 3 GTK+ 3 widgets to run an aptdaemon client
ii  python3-asn1crypto                   0.24.0-1                          all          Fast ASN.1 parser and serializer (Python 3)
ii  python3-blinker                      1.4+dfsg1-0.1                     all          fast, simple object-to-object and broadcast signaling library
ii  python3-brlapi                       5.5-4ubuntu2.0.1                  amd64        Braille display access via BRLTTY - Python3 bindings
ii  python3-bs4                          4.6.0-1                           all          error-tolerant HTML parser for Python 3
ii  python3-bsddb3                       6.1.0-1build4                     amd64        Python interface for Berkeley DB (Python 3.x)
ii  python3-cairo:amd64                  1.16.2-1                          amd64        Python3 bindings for the Cairo vector graphics library
ii  python3-certifi                      2018.1.18-2                       all          root certificates for validating SSL certs and verifying TLS hosts (python3)
ii  python3-cffi-backend                 1.11.5-1                          amd64        Foreign Function Interface for Python 3 calling C code - runtime
ii  python3-chardet                      3.0.4-1                           all          universal character encoding detector for Python3
ii  python3-cliapp                       1.20170827-1                      all          Python framework for Unix command line programs
ii  python3-commandnotfound              18.04.5                           all          Python 3 bindings for command-not-found.
ii  python3-crypto                       2.6.1-8ubuntu2                    amd64        cryptographic algorithms and protocols for Python 3
ii  python3-cryptography                 2.1.4-1ubuntu1.3                  amd64        Python library exposing cryptographic recipes and primitives (Python 3)
ii  python3-cups                         1.9.73-2                          amd64        Python3 bindings for CUPS
ii  python3-cupshelpers                  1.5.11-1ubuntu2                   all          Python utility modules around the CUPS printing system
ii  python3-dateutil                     2.6.1-1                           all          powerful extensions to the standard Python 3 datetime module
ii  python3-dbus                         1.2.6-1                           amd64        simple interprocess messaging system (Python 3 interface)
ii  python3-dbus.mainloop.pyqt5          5.10.1+dfsg-1ubuntu2              amd64        D-Bus Qt main loop support for Python 3
ii  python3-debconf                      1.5.66ubuntu1                     all          interact with debconf from Python 3
ii  python3-debian                       0.1.32                            all          Python 3 modules to work with Debian-related data formats
ii  python3-debianbts                    2.7.2                             all          Python interface to Debian's Bug Tracking System
ii  python3-defer                        1.0.6-2build1                     all          Small framework for asynchronous programming (Python 3)
ii  python3-dev                          3.6.7-1~18.04                     amd64        header files and a static library for Python (default)
ii  python3-distro-info                  0.18ubuntu0.18.04.1               all          information about distributions' releases (Python 3 module)
ii  python3-distupgrade                  1:18.04.38                        all          manage release upgrades
ii  python3-distutils                    3.6.9-1~18.04                     all          distutils package for Python 3.x
ii  python3-eyed3                        0.8.4-2                           all          Python module for id3-tags manipulation (Python 3 version)
ii  python3-feedparser                   5.2.1-1                           all          Universal Feed Parser for Python 3
ii  python3-gdbm:amd64                   3.6.9-1~18.04                     amd64        GNU dbm database support for Python 3.x
ii  python3-gi                           3.26.1-2ubuntu1                   amd64        Python 3 bindings for gobject-introspection libraries
ii  python3-gi-cairo                     3.26.1-2ubuntu1                   amd64        Python 3 Cairo bindings for the GObject library
ii  python3-html5lib                     0.999999999-1                     all          HTML parser/tokenizer based on the WHATWG HTML5 specification
ii  python3-httplib2                     0.9.2+dfsg-1ubuntu0.2             all          comprehensive HTTP client library written for Python3
ii  python3-icu                          1.9.8-0ubuntu1                    amd64        Python 3 extension wrapping the ICU C++ API
ii  python3-idna                         2.6-1                             all          Python IDNA2008 (RFC 5891) handling (Python 3)
ii  python3-jinja2                       2.10-1ubuntu0.18.04.1             all          small but fast and easy to use stand-alone template engine
ii  python3-jwt                          1.5.3+ds1-1                       all          Python 3 implementation of JSON Web Token
ii  python3-keyring                      10.6.0-1                          all          store and access your passwords safely - Python 3 version of the package
ii  python3-keyrings.alt                 3.0-1                             all          alternate backend implementations for python3-keyring
ii  python3-launchpadlib                 1.10.6-1                          all          Launchpad web services client library (Python 3)
ii  python3-lazr.restfulclient           0.13.5-1                          all          client for lazr.restful-based web services (Python 3)
ii  python3-lazr.uri                     1.0.3-2build1                     all          library for parsing, manipulating, and generating URIs
ii  python3-lib2to3                      3.6.9-1~18.04                     all          Interactive high-level object-oriented language (2to3, version 3.6)
ii  python3-louis                        3.5.0-1ubuntu0.3                  all          Python bindings for liblouis
ii  python3-lxml:amd64                   4.2.1-1ubuntu0.1                  amd64        pythonic binding for the libxml2 and libxslt libraries
ii  python3-macaroonbakery               1.1.3-1                           all          Higher-level macaroon operations for Python 3
ii  python3-magic                        2:0.4.15-1                        all          python3 interface to the libmagic file type identification library
ii  python3-mako                         1.0.7+ds1-1                       all          fast and lightweight templating for the Python 3 platform
ii  python3-markupsafe                   1.0-1build1                       amd64        HTML/XHTML/XML string library for Python 3
ii  python3-minimal                      3.6.7-1~18.04                     amd64        minimal subset of the Python language (default python3 version)
ii  python3-nacl                         1.1.2-1build1                     amd64        Python bindings to libsodium (Python 3)
ii  python3-netifaces                    0.10.4-0.1build4                  amd64        portable network interface information - Python 3.x
ii  python3-notify2                      0.3-3                             all          desktop notifications API for Python 3
ii  python3-numpy                        1:1.13.3-2ubuntu1                 amd64        Fast array facility to the Python 3 language
ii  python3-oauth                        1.0.1-5                           all          Python 3 library implementing of the OAuth protocol
ii  python3-oauthlib                     2.0.6-1                           all          generic, spec-compliant implementation of OAuth for Python3
ii  python3-olefile                      0.45.1-1                          all          Python module to read/write MS OLE2 files
ii  python3-openshot:amd64               0.1.9+dfsg1-3build1               amd64        OpenShot video library bindings for Python 3
ii  python3-pexpect                      4.2.1-1                           all          Python 3 module for automating interactive applications
ii  python3-pil:amd64                    5.1.0-1ubuntu0.3                  amd64        Python Imaging Library (Python3)
ii  python3-pip                          9.0.1-2.3~ubuntu1.18.04.2         all          Python package installer
ii  python3-pkg-resources                39.0.1-2                          all          Package Discovery and Resource Access using pkg_resources
ii  python3-problem-report               2.20.9-0ubuntu7.17                all          Python 3 library to handle problem reports
ii  python3-protobuf                     3.0.0-9.1ubuntu1                  amd64        Python 3 bindings for protocol buffers
ii  python3-ptyprocess                   0.5.2-1                           all          Run a subprocess in a pseudo terminal from Python 3
ii  python3-pyatspi                      2.26.0+dfsg-1                     all          Assistive Technology Service Provider Interface - Python3 bindings
ii  python3-pycurl                       7.43.0.1-0.2                      amd64        Python bindings to libcurl (Python 3)
ii  python3-pygments                     2.2.0+dfsg-1                      all          syntax highlighting package written in Python 3
ii  python3-pymacaroons                  0.13.0-1                          all          Macaroon library for Python 3
ii  python3-pyqt5                        5.10.1+dfsg-1ubuntu2              amd64        Python 3 bindings for Qt5
ii  python3-pyqt5.qsci                   2.10.2+dfsg-4                     amd64        Python 3 bindings for QScintilla 2 with Qt 5
ii  python3-pyqt5.qtsql                  5.10.1+dfsg-1ubuntu2              amd64        Python 3 bindings for Qt5's SQL module
ii  python3-pyqt5.qtsvg                  5.10.1+dfsg-1ubuntu2              amd64        Python 3 bindings for Qt5's SVG module
ii  python3-pyqt5.qtwebkit               5.10.1+dfsg-1ubuntu2              amd64        Python 3 bindings for Qt5's WebKit module
ii  python3-pysimplesoap                 1.16-2                            all          simple and lightweight SOAP Library (Python 3)
ii  python3-renderpm:amd64               3.4.0-3ubuntu0.1                  amd64        python low level render interface
ii  python3-reportlab                    3.4.0-3ubuntu0.1                  all          ReportLab library to create PDF documents using Python3
ii  python3-reportlab-accel:amd64        3.4.0-3ubuntu0.1                  amd64        C coded extension accelerator for the ReportLab Toolkit
ii  python3-requests                     2.18.4-2ubuntu0.1                 all          elegant and simple HTTP library for Python3, built for human beings
ii  python3-requests-unixsocket          0.1.5-3                           all          Use requests to talk HTTP via a UNIX domain socket - Python 3.x
ii  python3-rfc3339                      1.0-4                             all          parser and generator of RFC 3339-compliant timestamps (Python 3)
ii  python3-scour                        0.36-2                            all          SVG scrubber and optimizer (Python 3 module)
ii  python3-secretstorage                2.3.1-2                           all          Python module for storing secrets - Python 3.x version
ii  python3-setuptools                   39.0.1-2                          all          Python3 Distutils Enhancements
ii  python3-simplejson                   3.13.2-1                          amd64        simple, fast, extensible JSON encoder/decoder for Python 3.x
ii  python3-sip                          4.19.7+dfsg-1ubuntu0.1            amd64        Python 3/C++ bindings generator runtime library
ii  python3-six                          1.11.0-2                          all          Python 2 and 3 compatibility library (Python 3 interface)
ii  python3-software-properties          0.96.24.32.14                     all          manage the repositories that you install software from
ii  python3-speechd                      0.8.8-1ubuntu1                    all          Python interface to Speech Dispatcher
ii  python3-systemd                      234-1build1                       amd64        Python 3 bindings for systemd
ii  python3-tk:amd64                     3.6.9-1~18.04                     amd64        Tkinter - Writing Tk applications with Python 3.x
ii  python3-tz                           2018.3-2                          all          Python3 version of the Olson timezone database
ii  python3-tzlocal                      1.5.1-1                           all          tzinfo object for the local timezone (Python 3 version)
ii  python3-update-manager               1:18.04.11.13                     all          python 3.x module for update-manager
ii  python3-urllib3                      1.22-1ubuntu0.18.04.1             all          HTTP library with thread-safe connection pooling for Python3
ii  python3-wadllib                      1.3.2-3ubuntu0.18.04.1            all          Python 3 library for navigating WADL files
ii  python3-webencodings                 0.5-2                             all          Python implementation of the WHATWG Encoding standard
ii  python3-wheel                        0.30.0-0.2                        all          built-package format for Python
ii  python3-xapian                       1.4.5-1ubuntu3                    amd64        Xapian search engine interface for Python3
ii  python3-xdg                          0.25-4ubuntu1                     all          Python 3 library to access freedesktop.org standards
ii  python3-xkit                         0.5.0ubuntu2                      all          library for the manipulation of xorg.conf files (Python 3)
ii  python3-yaml                         3.12-1build2                      amd64        YAML parser and emitter for Python3
ii  python3-zmq                          16.0.2-2build2                    amd64        Python3 bindings for 0MQ library
ii  python3-zope.interface               4.3.2-1build2                     amd64        Interfaces for Python3
ii  python3.6                            3.6.9-1~18.04ubuntu1.1            amd64        Interactive high-level object-oriented language (version 3.6)
ii  python3.6-dev                        3.6.9-1~18.04ubuntu1.1            amd64        Header files and a static library for Python (v3.6)
ii  python3.6-minimal                    3.6.9-1~18.04ubuntu1.1            amd64        Minimal subset of the Python language (version 3.6)

```

**Comment by Jerome-Maurin** [comment]
Hi,

Like explained in the README.md file you need to use at least the vmdb2 version specified in the yaml file name.

I see here that you used vmdb2 0.12 which is older than 0.14.1.

You need to use 0.14.1 or later.
